image: maven:3.5-jdk-8

stages:
  - version_info
  - version_commit
  - build
  
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s ./settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository/
  key: ${CI_BUILD_REF_NAME}

version_info_deploy:
  stage: version_info
  only:
    refs:
      - triggers
      - web
  except:
    variables:
      - $RELEASE == "TRUE"
  script:
    # Version information
    - echo datetime=`date +%Y-%m-%d_%H:%M:%S` > ver.txt
    - echo version=${VERSION}-SNAPSHOT >> ver.txt
    - cat ver.txt
  artifacts:
    paths:
      - ver.txt

version_info_release:
  stage: version_info
  only:
    refs:
      - web
    variables:
      - $RELEASE == "TRUE"
  script:
    - echo datetime=`date +%Y-%m-%d_%H:%M:%S` > ver.txt
    - echo version=${VERSION} >> ver.txt
    - cat ver.txt
  artifacts:
    paths:
      - ver.txt

version_commit:
  stage: version_commit
  # Only commit version to SVN when building off svn/dev, which mirrors SVN
  only:
    refs:
      - svn/dev
  # Don't commit on pushes, otherwise might cause an infinite loop!
  except:
    refs:
      - pushes
  script:
    - ls
    - cat ver.txt
    # - svn --username ${SVN_USER} --password ${SVN_PASS} checkout svn://107.170.10.188:8080/Semoss/dev SemossVer --depth empty
    # - cd SemossVer
    # - svn --username ${SVN_USER} --password ${SVN_PASS} up ver.txt
    # - cp -rf ../ver.txt ver.txt
    # - svn --username ${SVN_USER} --password ${SVN_PASS} status -u
    # - svn --username ${SVN_USER} --password ${SVN_PASS} commit -m "VERSION"
    # - cd ..
    # - rm -rf SemossVer

# Does not push to maven central
build_dev:
  stage: build
  # See https://docs.gitlab.com/ee/ci/yaml/#only-and-except-simplified
  only:
    refs:
      - pushes
  except:
    variables:
      - $RELEASE == "TRUE"
  script:
    - apt-get update
    - apt-get install -y openjfx
    - mvn $MAVEN_CLI_OPTS clean install -Dci.version=${VERSION}-SNAPSHOT
    # So that the cache takes up less space
    - rm -rf .m2/repository/org/semoss
  artifacts:
    paths:
      - target/semoss-${VERSION}-SNAPSHOT.jar

# Pushes to maven central
build_deploy:
  stage: build
  only:
    refs:
      - triggers
      - web
  except:
    variables:
      - $RELEASE == "TRUE"
  script:
    - ls
    - cat ver.txt
    - apt-get update
    - apt-get install -y openjfx
    - apt-get install -y gnupg2
    - gpg2 --batch --import <(echo "$GPG_PRIVATE_KEY")
    - mvn $MAVEN_CLI_OPTS deploy -P deploy -Dci.version=${VERSION}-SNAPSHOT
    # So that the cache takes up less space
    - rm -rf .m2/repository/org/semoss
  artifacts:
    paths:
      - target/semoss-${VERSION}-SNAPSHOT.jar
      
# Releases to maven central
build_release:
  stage: build
  # Only release if explicitly triggered on web and the RELEASE variable is set to TRUE
  only:
    refs:
      - web
    variables:
      - $RELEASE == "TRUE"
  script:
    - ls
    - cat ver.txt
    - apt-get update
    - apt-get install -y openjfx
    - apt-get install -y gnupg2
    - gpg2 --batch --import <(echo "$GPG_PRIVATE_KEY")
    - mvn $MAVEN_CLI_OPTS deploy -P deploy -Dci.version=${VERSION}
    # So that the cache takes up less space
    - rm -rf .m2/repository/org/semoss
  artifacts:
    paths:
      - target/semoss-${VERSION}.jar
