image: maven:3.5-jdk-8

stages:
  - build

before_script:
  - apt-get update
  - apt-get install -y openjfx
  
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
  paths:
    - target/
    - .m2/repository/
  key: ${CI_BUILD_REF_NAME}
  
build:
  stage: build
  script:
    - echo $JAVA_HOME
    - ls $JAVA_HOME
    - ls $JAVA_HOME/lib/
    - ls /usr/lib/jvm/
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/
      - .m2/repository/